version: '3.7'

services:
  asap:
    container_name: kream
    build: .
    image: kream:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JVM_OPTS=-Xmx1g -Xms1g
      - TZ=Asia/Seoul
      - "--jasypt.encryptor.key=${PASSWD}"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"