spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(ZeayKQ67Q/vpR8uZB6W6N9bUFWTtxoEc3kvmJZxAxqbBny1q7Yck7SMpBnMLHJpKOh8p4rqnpFY=)
    username: ENC(aiH8hrw9E+ErSwLkRn3Kag==)
    password: ENC(E1Hv9nlSKmckP9SvajbWcw==)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(SmDvKpBjBBcPYbsJarsAkudMLpQcmuYq/Y4AkYvsbvg=)
    password: ENC(VGBLY+EdcKIj60bBvIN8rEmwUjJFl2XljFsxGrpDEhU=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: secret=asd123
  jpa:
    show-sql: true
  security.oauth2.client:
    registration.naver:
      client-name: naver
      client-id: ENC(uaS92q0OX0JX0K0OMJMoqrpDnLmScIKHKQL0Qu/xFrI=)
      client-secret: ENC(APJ7iRZxSOTvVH5rqhhXDj+tRcn6D419)
      redirect-uri: http://localhost:8080/login/oauth2/code/naver
      authorization-grant-type: authorization_code
      scope: name, email
    provider.naver:
      authorization-uri: https://nid.naver.com/oauth2.0/authorize
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
      user-name-attribute: response

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
cors:
  host: http://localhost:3000