spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(YiBT9wshgO0orwLbyOnH/+r2pq7jogZOehgrprlWkNbe3l/hmiIqWqj50QkPSSHE)
    username: ENC(+rzyNEuL8hk5/1Sos4TfHg==)
    password: ENC(01n7L6C8DoscJzluIfzdPg==)
  mail:
    host: smtp.gmail.com
    port: 587
    username: shhwang0930@gmail.com
    password: zowufvotifzjosnn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
  redis:
    host: localhost
    port: 6379